//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMBFormBuilder.Resources
{
    using System;

    /// <summary>
    /// Provides strongly typed access to DMBFormBuilder data annotation localization resources.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DMBFormBuilderDataAnnotationLocalization
    {
        private static System.Resources.ResourceManager? resourceMan;

        private static System.Globalization.CultureInfo? resourceCulture;

        /// <summary>
        /// Initializes a new instance of the generated localization resource accessor.
        /// </summary>
        public DMBFormBuilderDataAnnotationLocalization()
        {
        }

        /// <summary>
        /// Gets the resource manager used to retrieve data annotation localized strings.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                resourceMan ??= new System.Resources.ResourceManager("DMBFormBuilder.Resources.DMBFormBuilderDataAnnotationLocalization", typeof(DMBFormBuilderDataAnnotationLocalization).Assembly);
                return resourceMan;
            }
        }

        /// <summary>
        /// Gets or sets the culture used by the generated data annotation resource accessor.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Captcha_Image_Error</c> resource.


        /// </summary>

        public static string FormBuilder_Captcha_Image_Error => ResourceManager.GetString("FormBuilder_Captcha_Image_Error", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Captcha_Invalid</c> resource.


        /// </summary>

        public static string FormBuilder_Captcha_Invalid => ResourceManager.GetString("FormBuilder_Captcha_Invalid", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Captcha_Required</c> resource.


        /// </summary>

        public static string FormBuilder_Captcha_Required => ResourceManager.GetString("FormBuilder_Captcha_Required", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Company</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Company => ResourceManager.GetString("FormBuilder_Field_Company", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Company_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Company_Prompt => ResourceManager.GetString("FormBuilder_Field_Company_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_AsciiCode</c> resource.


        /// </summary>

        public static string FormBuilder_Field_AsciiCode => ResourceManager.GetString("FormBuilder_Field_AsciiCode", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_AsciiCode_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_AsciiCode_Prompt => ResourceManager.GetString("FormBuilder_Field_AsciiCode_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_AsciiInvalid</c> resource.


        /// </summary>

        public static string FormBuilder_Field_AsciiInvalid => ResourceManager.GetString("FormBuilder_Field_AsciiInvalid", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_AcceptTerms</c> resource.


        /// </summary>

        public static string FormBuilder_Field_AcceptTerms => ResourceManager.GetString("FormBuilder_Field_AcceptTerms", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Badge_Ascii</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Badge_Ascii => ResourceManager.GetString("FormBuilder_Field_Badge_Ascii", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Badge_Float</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Badge_Float => ResourceManager.GetString("FormBuilder_Field_Badge_Float", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Badge_Numeric</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Badge_Numeric => ResourceManager.GetString("FormBuilder_Field_Badge_Numeric", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Badge_NoHtml</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Badge_NoHtml => ResourceManager.GetString("FormBuilder_Field_Badge_NoHtml", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Badge_Unix</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Badge_Unix => ResourceManager.GetString("FormBuilder_Field_Badge_Unix", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_BoolMustBeFalse</c> resource.


        /// </summary>

        public static string FormBuilder_Field_BoolMustBeFalse => ResourceManager.GetString("FormBuilder_Field_BoolMustBeFalse", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_BoolMustBeTrue</c> resource.


        /// </summary>

        public static string FormBuilder_Field_BoolMustBeTrue => ResourceManager.GetString("FormBuilder_Field_BoolMustBeTrue", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Disabled</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Disabled => ResourceManager.GetString("FormBuilder_Field_Disabled", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Disabled_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Disabled_Prompt => ResourceManager.GetString("FormBuilder_Field_Disabled_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Color</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Color => ResourceManager.GetString("FormBuilder_Field_Color", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_DueDate</c> resource.


        /// </summary>

        public static string FormBuilder_Field_DueDate => ResourceManager.GetString("FormBuilder_Field_DueDate", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_DueDate_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_DueDate_Prompt => ResourceManager.GetString("FormBuilder_Field_DueDate_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_DueDateTime</c> resource.


        /// </summary>

        public static string FormBuilder_Field_DueDateTime => ResourceManager.GetString("FormBuilder_Field_DueDateTime", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_DueDateTime_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_DueDateTime_Prompt => ResourceManager.GetString("FormBuilder_Field_DueDateTime_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Email</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Email => ResourceManager.GetString("FormBuilder_Field_Email", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_EnableNotifications</c> resource.


        /// </summary>

        public static string FormBuilder_Field_EnableNotifications => ResourceManager.GetString("FormBuilder_Field_EnableNotifications", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_EmailInvalid</c> resource.


        /// </summary>

        public static string FormBuilder_Field_EmailInvalid => ResourceManager.GetString("FormBuilder_Field_EmailInvalid", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_EmailOptional</c> resource.


        /// </summary>

        public static string FormBuilder_Field_EmailOptional => ResourceManager.GetString("FormBuilder_Field_EmailOptional", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_EmailOptional_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_EmailOptional_Prompt => ResourceManager.GetString("FormBuilder_Field_EmailOptional_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Email_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Email_Prompt => ResourceManager.GetString("FormBuilder_Field_Email_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_FirstName</c> resource.


        /// </summary>

        public static string FormBuilder_Field_FirstName => ResourceManager.GetString("FormBuilder_Field_FirstName", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_FirstName_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_FirstName_Prompt => ResourceManager.GetString("FormBuilder_Field_FirstName_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_FloatValue</c> resource.


        /// </summary>

        public static string FormBuilder_Field_FloatValue => ResourceManager.GetString("FormBuilder_Field_FloatValue", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_FloatValue_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_FloatValue_Prompt => ResourceManager.GetString("FormBuilder_Field_FloatValue_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_FormatInvalid</c> resource.


        /// </summary>

        public static string FormBuilder_Field_FormatInvalid => ResourceManager.GetString("FormBuilder_Field_FormatInvalid", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_HiddenEmail</c> resource.


        /// </summary>

        public static string FormBuilder_Field_HiddenEmail => ResourceManager.GetString("FormBuilder_Field_HiddenEmail", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_HiddenEmail_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_HiddenEmail_Prompt => ResourceManager.GetString("FormBuilder_Field_HiddenEmail_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_HiddenLabel</c> resource.


        /// </summary>

        public static string FormBuilder_Field_HiddenLabel => ResourceManager.GetString("FormBuilder_Field_HiddenLabel", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_HiddenLabel_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_HiddenLabel_Prompt => ResourceManager.GetString("FormBuilder_Field_HiddenLabel_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_InlineEmail</c> resource.


        /// </summary>

        public static string FormBuilder_Field_InlineEmail => ResourceManager.GetString("FormBuilder_Field_InlineEmail", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_InlineEmail_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_InlineEmail_Prompt => ResourceManager.GetString("FormBuilder_Field_InlineEmail_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_InlineCode</c> resource.


        /// </summary>

        public static string FormBuilder_Field_InlineCode => ResourceManager.GetString("FormBuilder_Field_InlineCode", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_InlineCode_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_InlineCode_Prompt => ResourceManager.GetString("FormBuilder_Field_InlineCode_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_LeftLabel</c> resource.


        /// </summary>

        public static string FormBuilder_Field_LeftLabel => ResourceManager.GetString("FormBuilder_Field_LeftLabel", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Message</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Message => ResourceManager.GetString("FormBuilder_Field_Message", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Message_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Message_Prompt => ResourceManager.GetString("FormBuilder_Field_Message_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Month</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Month => ResourceManager.GetString("FormBuilder_Field_Month", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Month_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Month_Prompt => ResourceManager.GetString("FormBuilder_Field_Month_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Nickname</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Nickname => ResourceManager.GetString("FormBuilder_Field_Nickname", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Nickname_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Nickname_Prompt => ResourceManager.GetString("FormBuilder_Field_Nickname_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_NoHtmlInvalid</c> resource.


        /// </summary>

        public static string FormBuilder_Field_NoHtmlInvalid => ResourceManager.GetString("FormBuilder_Field_NoHtmlInvalid", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_NumericValue</c> resource.


        /// </summary>

        public static string FormBuilder_Field_NumericValue => ResourceManager.GetString("FormBuilder_Field_NumericValue", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_NumericValue_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_NumericValue_Prompt => ResourceManager.GetString("FormBuilder_Field_NumericValue_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Notes</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Notes => ResourceManager.GetString("FormBuilder_Field_Notes", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Notes_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Notes_Prompt => ResourceManager.GetString("FormBuilder_Field_Notes_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Priority</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Priority => ResourceManager.GetString("FormBuilder_Field_Priority", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Range</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Range => ResourceManager.GetString("FormBuilder_Field_Range", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Slider</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Slider => ResourceManager.GetString("FormBuilder_Field_Slider", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Time</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Time => ResourceManager.GetString("FormBuilder_Field_Time", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Time_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Time_Prompt => ResourceManager.GetString("FormBuilder_Field_Time_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_UnixCode</c> resource.


        /// </summary>

        public static string FormBuilder_Field_UnixCode => ResourceManager.GetString("FormBuilder_Field_UnixCode", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_UnixCode_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_UnixCode_Prompt => ResourceManager.GetString("FormBuilder_Field_UnixCode_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_UnixInvalid</c> resource.


        /// </summary>

        public static string FormBuilder_Field_UnixInvalid => ResourceManager.GetString("FormBuilder_Field_UnixInvalid", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_MaxLength</c> resource.


        /// </summary>

        public static string FormBuilder_Field_MaxLength => ResourceManager.GetString("FormBuilder_Field_MaxLength", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_MinLength</c> resource.


        /// </summary>

        public static string FormBuilder_Field_MinLength => ResourceManager.GetString("FormBuilder_Field_MinLength", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Password</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Password => ResourceManager.GetString("FormBuilder_Field_Password", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_PasswordConfirm</c> resource.


        /// </summary>

        public static string FormBuilder_Field_PasswordConfirm => ResourceManager.GetString("FormBuilder_Field_PasswordConfirm", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_PasswordConfirm_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_PasswordConfirm_Prompt => ResourceManager.GetString("FormBuilder_Field_PasswordConfirm_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_PasswordCompare</c> resource.


        /// </summary>

        public static string FormBuilder_Field_PasswordCompare => ResourceManager.GetString("FormBuilder_Field_PasswordCompare", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_PasswordCurrent</c> resource.


        /// </summary>

        public static string FormBuilder_Field_PasswordCurrent => ResourceManager.GetString("FormBuilder_Field_PasswordCurrent", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_PasswordCurrent_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_PasswordCurrent_Prompt => ResourceManager.GetString("FormBuilder_Field_PasswordCurrent_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_PasswordHide</c> resource.


        /// </summary>

        public static string FormBuilder_Field_PasswordHide => ResourceManager.GetString("FormBuilder_Field_PasswordHide", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_PasswordInvalid</c> resource.


        /// </summary>

        public static string FormBuilder_Field_PasswordInvalid => ResourceManager.GetString("FormBuilder_Field_PasswordInvalid", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_PasswordNew</c> resource.


        /// </summary>

        public static string FormBuilder_Field_PasswordNew => ResourceManager.GetString("FormBuilder_Field_PasswordNew", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_PasswordNew_Prompt</c> resource.


        /// </summary>

        public static string FormBuilder_Field_PasswordNew_Prompt => ResourceManager.GetString("FormBuilder_Field_PasswordNew_Prompt", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_PasswordShow</c> resource.


        /// </summary>

        public static string FormBuilder_Field_PasswordShow => ResourceManager.GetString("FormBuilder_Field_PasswordShow", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_PasswordStrength</c> resource.


        /// </summary>

        public static string FormBuilder_Field_PasswordStrength => ResourceManager.GetString("FormBuilder_Field_PasswordStrength", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Field_Required</c> resource.


        /// </summary>

        public static string FormBuilder_Field_Required => ResourceManager.GetString("FormBuilder_Field_Required", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>FormBuilder_Form_RequiredLegend</c> resource.


        /// </summary>

        public static string FormBuilder_Form_RequiredLegend => ResourceManager.GetString("FormBuilder_Form_RequiredLegend", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>Compare_Password_ErrorMessage</c> resource.


        /// </summary>

        public static string Compare_Password_ErrorMessage => ResourceManager.GetString("Compare_Password_ErrorMessage", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>MaxLengthAttribute_ErrorMessage</c> resource.


        /// </summary>

        public static string MaxLengthAttribute_ErrorMessage => ResourceManager.GetString("MaxLengthAttribute_ErrorMessage", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>MinLengthAttribute_ErrorMessage</c> resource.


        /// </summary>

        public static string MinLengthAttribute_ErrorMessage => ResourceManager.GetString("MinLengthAttribute_ErrorMessage", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>Password_ErrorMessage</c> resource.


        /// </summary>

        public static string Password_ErrorMessage => ResourceManager.GetString("Password_ErrorMessage", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>Low</c> resource.


        /// </summary>

        public static string Low => ResourceManager.GetString("Low", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>Medium</c> resource.


        /// </summary>

        public static string Medium => ResourceManager.GetString("Medium", resourceCulture) ?? string.Empty;

        /// <summary>


        /// Gets the localized string for the <c>High</c> resource.


        /// </summary>

        public static string High => ResourceManager.GetString("High", resourceCulture) ?? string.Empty;
    }
}
