//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace DMBFormBuilder.Resources
{
    using System;

    /// <summary>
    /// Provides strongly typed access to DMBFormBuilder internal localization resources.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DMBFormBuilderInternalLocalization
    {
        private static System.Resources.ResourceManager? resourceMan;

        private static System.Globalization.CultureInfo? resourceCulture;

        /// <summary>
        /// Initializes a new instance of the generated localization resource accessor.
        /// </summary>
        public DMBFormBuilderInternalLocalization()
        {
        }

        /// <summary>
        /// Gets the resource manager used to retrieve internal localized strings.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                resourceMan ??= new System.Resources.ResourceManager("DMBFormBuilder.Resources.DMBFormBuilderInternalLocalization", typeof(DMBFormBuilderInternalLocalization).Assembly);
                return resourceMan;
            }
        }

        /// <summary>
        /// Gets or sets the culture used by the generated internal resource accessor.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        /// <summary>
        /// Gets the localized string for the <c>FormBuilder_Captcha_Invalid_Message</c> resource.
        /// </summary>
        public static string FormBuilder_Captcha_Invalid_Message => ResourceManager.GetString("FormBuilder_Captcha_Invalid_Message", resourceCulture) ?? string.Empty;

        /// <summary>
        /// Gets the localized string for the <c>FormBuilder_Captcha_Invalid_Title</c> resource.
        /// </summary>
        public static string FormBuilder_Captcha_Invalid_Title => ResourceManager.GetString("FormBuilder_Captcha_Invalid_Title", resourceCulture) ?? string.Empty;

        /// <summary>
        /// Gets the localized string for the <c>FormBuilder_Captcha_Valid_Message</c> resource.
        /// </summary>
        public static string FormBuilder_Captcha_Valid_Message => ResourceManager.GetString("FormBuilder_Captcha_Valid_Message", resourceCulture) ?? string.Empty;

        /// <summary>
        /// Gets the localized string for the <c>FormBuilder_Captcha_Valid_Title</c> resource.
        /// </summary>
        public static string FormBuilder_Captcha_Valid_Title => ResourceManager.GetString("FormBuilder_Captcha_Valid_Title", resourceCulture) ?? string.Empty;
    }
}
